import type { LabCategory, LabSummary } from '@domain/models/lab.model';

/**
 * Ordered catalog of the 16 V1 laboratories. Presentation-facing only; full
 * lab configs (stages, experiments, challenges) are added in a later phase.
 */
export const LAB_CATALOG: readonly LabSummary[] = [
  {
    id: 'lab-01-tensors',
    number: 1,
    slug: '01-fundamentos-de-tensores',
    title: 'Fundamentos de Tensores',
    description: 'O que são tensores, rank, shape, dtype e como os dados viram tensores.',
    estimatedMinutes: 20,
    concepts: ['tensor', 'escalar', 'vetor', 'matriz', 'rank', 'shape', 'size', 'dtype'],
    prerequisites: [],
    category: 'tensors',
  },
  {
    id: 'lab-02-manipulation',
    number: 2,
    slug: '02-manipulacao-de-tensores',
    title: 'Manipulação de Tensores',
    description: 'reshape, flatten, expandDims e squeeze para reorganizar dados.',
    estimatedMinutes: 20,
    concepts: ['reshape', 'flatten', 'expandDims', 'squeeze'],
    prerequisites: ['lab-01-tensors'],
    category: 'operations',
  },
  {
    id: 'lab-03-elementwise',
    number: 3,
    slug: '03-operacoes-elemento-a-elemento',
    title: 'Operações Elemento a Elemento',
    description: 'adição, subtração, multiplicação, divisão, potência e raiz.',
    estimatedMinutes: 20,
    concepts: ['operacoes-elementares', 'broadcasting'],
    prerequisites: ['lab-02-manipulation'],
    category: 'operations',
  },
  {
    id: 'lab-04-reductions',
    number: 4,
    slug: '04-operacoes-de-reducao',
    title: 'Operações de Redução',
    description: 'sum, mean, min e max ao longo de eixos específicos.',
    estimatedMinutes: 20,
    concepts: ['reducao', 'media', 'soma', 'eixo'],
    prerequisites: ['lab-03-elementwise'],
    category: 'operations',
  },
  {
    id: 'lab-05-matrix',
    number: 5,
    slug: '05-operacoes-matriciais',
    title: 'Operações Matriciais',
    description: 'transpose e multiplicação de matrizes (matMul).',
    estimatedMinutes: 25,
    concepts: ['transpose', 'matMul', 'produto-escalar'],
    prerequisites: ['lab-04-reductions'],
    category: 'operations',
  },
  {
    id: 'lab-06-broadcasting',
    number: 6,
    slug: '06-broadcasting',
    title: 'Broadcasting',
    description: 'Regras de broadcast, formas compatíveis e expansão implícita.',
    estimatedMinutes: 25,
    concepts: ['broadcasting', 'shape'],
    prerequisites: ['lab-05-matrix'],
    category: 'operations',
  },
  {
    id: 'lab-07-linear-algebra',
    number: 7,
    slug: '07-algebra-linear-aplicada',
    title: 'Álgebra Linear Aplicada',
    description: 'Vetores, produto escalar e transformações lineares em 2D.',
    estimatedMinutes: 30,
    concepts: ['transformacao-linear', 'produto-escalar', 'vetor'],
    prerequisites: ['lab-06-broadcasting'],
    category: 'operations',
  },
  {
    id: 'lab-08-ml-fundamentals',
    number: 8,
    slug: '08-fundamentos-de-machine-learning',
    title: 'Fundamentos de Machine Learning',
    description: 'dataset, features, labels, treino/validação, loss, época e batch.',
    estimatedMinutes: 30,
    concepts: ['dataset', 'feature', 'label', 'loss', 'epoca', 'batch', 'learning-rate'],
    prerequisites: ['lab-07-linear-algebra'],
    category: 'ml',
  },
  {
    id: 'lab-09-linear-regression',
    number: 9,
    slug: '09-regressao-linear',
    title: 'Regressão Linear',
    description: 'y = wx + b, MSE e ajuste de uma reta aos dados.',
    estimatedMinutes: 30,
    concepts: ['regressao-linear', 'mse', 'predicao'],
    prerequisites: ['lab-08-ml-fundamentals'],
    category: 'ml',
  },
  {
    id: 'lab-10-gradient-descent',
    number: 10,
    slug: '10-descida-do-gradiente',
    title: 'Descida do Gradiente',
    description: 'Superfície de custo, gradiente, learning rate e convergência.',
    estimatedMinutes: 35,
    concepts: ['gradiente', 'learning-rate', 'convergencia', 'minimo-local'],
    prerequisites: ['lab-09-linear-regression'],
    category: 'ml',
  },
  {
    id: 'lab-11-neuron',
    number: 11,
    slug: '11-o-neuronio',
    title: 'O Neurônio',
    description: 'Entradas, pesos, bias, soma ponderada e ativação.',
    estimatedMinutes: 30,
    concepts: ['neuronio', 'peso', 'bias', 'soma-ponderada', 'ativacao'],
    prerequisites: ['lab-10-gradient-descent'],
    category: 'neural-networks',
  },
  {
    id: 'lab-12-activations',
    number: 12,
    slug: '12-funcoes-de-ativacao',
    title: 'Funções de Ativação',
    description: 'Sigmoid, ReLU, Tanh e Softmax: fórmulas, gráficos e derivadas.',
    estimatedMinutes: 30,
    concepts: ['sigmoid', 'relu', 'tanh', 'softmax', 'derivada'],
    prerequisites: ['lab-11-neuron'],
    category: 'neural-networks',
  },
  {
    id: 'lab-13-neural-networks',
    number: 13,
    slug: '13-redes-neurais',
    title: 'Redes Neurais',
    description: 'Camadas, propagação direta, loss, backpropagation e treino.',
    estimatedMinutes: 40,
    concepts: ['camada', 'forward-propagation', 'backpropagation', 'treino'],
    prerequisites: ['lab-12-activations'],
    category: 'neural-networks',
  },
  {
    id: 'lab-14-classification',
    number: 14,
    slug: '14-classificacao-e-fronteiras-de-decisao',
    title: 'Classificação e Fronteiras de Decisão',
    description: 'Classificação binária/multiclasse, fronteiras de decisão e o problema XOR.',
    estimatedMinutes: 40,
    concepts: ['classificacao', 'fronteira-de-decisao', 'xor'],
    prerequisites: ['lab-13-neural-networks'],
    category: 'neural-networks',
  },
  {
    id: 'lab-15-images',
    number: 15,
    slug: '15-imagens-como-tensores',
    title: 'Imagens como Tensores',
    description: 'Imagem → pixels → tensor, canais RGB, grayscale, resize e normalização.',
    estimatedMinutes: 35,
    concepts: ['imagem', 'rgb', 'grayscale', 'normalizacao'],
    prerequisites: ['lab-14-classification'],
    category: 'images',
  },
  {
    id: 'lab-16-memory',
    number: 16,
    slug: '16-gerenciamento-de-memoria',
    title: 'Gerenciamento de Memória',
    description: 'tf.memory(), tf.dispose(), tf.tidy() e boas práticas contra vazamentos.',
    estimatedMinutes: 30,
    concepts: ['memoria', 'dispose', 'tidy', 'vazamento'],
    prerequisites: ['lab-15-images'],
    category: 'memory',
  },
];

/** Human-readable labels for lab categories, used by catalog filters. */
export const LAB_CATEGORY_LABELS: Record<LabCategory, string> = {
  tensors: 'Tensores',
  operations: 'Operações',
  ml: 'Machine Learning',
  'neural-networks': 'Redes Neurais',
  images: 'Imagens',
  memory: 'Memória',
};

/** Finds a lab summary by its URL slug. */
export function findLabBySlug(slug: string): LabSummary | undefined {
  return LAB_CATALOG.find((lab) => lab.slug === slug);
}
